### ISSUE TITLE
URI mismatch for Taxon 

### ISSUE THREAD

**Issue by laurianvm** [MareGraph-EU/assets#4]
Could there be a typo in the url's used to refer to Taxon in attribute-trait.ttl?

in attribute-trait ontology the url of Taxon has /taxa-name/   
(e.g. https://github.com/MareGraph-EU/assets/blob/main/ontologies/attribute-trait/latest/attribute-trait.ttl#L92)
while the prefix in taxon-name ontology uses /taxon-name/  
(https://github.com/MareGraph-EU/assets/blob/main/ontologies/taxon-name/latest/taxon-name.ttl#L1)

**Comment by giorgialodi** [comment]
yep, this is a bug! Thanks for pointing it out!

**Comment by laurianvm** [comment]
replaced all 'taxa-' with 'taxon-'

**Comment by giorgialodi** [comment]
guys, we need to pay attention to the logic of the repository. It is not only a matter to change the latest, which of course of utmost importance, there are also versions that are now not aligned with the latest one.

**Comment by laurianvm** [comment]
replaced 'taxa-' with 'taxon-' for v0.1 and v0.2
(for taxon-name/v0.1 there wasn't a conflict between 'taxa-' and 'taxon-', so no replacement needed)

@giorgialodi could you double check and close if okay? :)

**Comment by bart-v** [comment]
Working with versions in folders like /v0.1 and /v0.2 is completely against the git versioning/tagging principles.
Why don't we use tags (or similar) for this?

**Comment by giorgialodi** [comment]
We can do whatever you want. In the Italian practice we adopt this practice since it is more immediate especially for people who are not so familiar with github (and this is particularly true in the Italian Public Sector).
BTW: we do not have to change all the previous versions, just the latest one that is in latest directory and v0.2 in this case. 
In italy the latest directory serves for redirecting rules in w3id.org and so we followed this pattern as well which is quite convenient from a technical perspective.

**Comment by laurianvm** [comment]
apologies, misread another comment and consequently updated taxa- to taxon- for all versions in the other branches

I agree with Giorgia that this is more clear for people not (yet) acquainted with git/github (this is not only the case for the Italian Public Sector)
